development:
  host: http://localhost:4001/
  email: roadtang@gmail.com
  password: password
  # api_key: <your api key here>
staging:
  host: staging.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>
production:
  host: www.example.com
  email: john@doe.net
  password: apassword
  # api_key: <your api key here>